name: dl_worker_test
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
      - develop


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Bring SourceCode
      - name: Checkout
        uses: actions/checkout@v2
    if: github.event.pull_request.merged == false
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: startsWith(github.head_ref, 'hotfix') == false || github.base_ref == 'develop'
      - name: Test1
        uses: actions/checkout@v2
        if: startsWith(github.head_ref, 'hotfix') == true && github.base_ref == 'master'
    if:  github.event.pull_request.merged == true
